[2024-02-27T15:05:38.011-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-27T14:43:15.404695+00:00 [queued]>
[2024-02-27T15:05:38.022-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-27T14:43:15.404695+00:00 [queued]>
[2024-02-27T15:05:38.023-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 1
[2024-02-27T15:05:38.037-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-27 14:43:15.404695+00:00
[2024-02-27T15:05:38.047-0500] {standard_task_runner.py:57} INFO - Started process 9099 to run task
[2024-02-27T15:05:38.055-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'upload_to_s3', 'manual__2024-02-27T14:43:15.404695+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmp8c6s17t0']
[2024-02-27T15:05:38.059-0500] {standard_task_runner.py:85} INFO - Job 71: Subtask upload_to_s3
[2024-02-27T15:05:38.208-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-27T14:43:15.404695+00:00 [running]> on host venkatasaismbp.hsd1.nj.comcast.net
[2024-02-27T15:05:38.429-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T14:43:15.404695+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T14:43:15.404695+00:00'
[2024-02-27T15:05:38.462-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-02-27T15:05:38.464-0500] {connection_wrapper.py:382} INFO - AWS Connection (conn_id='aws_conn_s3', conn_type='aws') credentials retrieved from login and ***.
[2024-02-27T15:06:29.200-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-02-27T15:06:29.219-0500] {process_utils.py:131} INFO - Sending 15 to group 9099. PIDs of all processes in the group: [9099]
[2024-02-27T15:06:29.220-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 9099
[2024-02-27T15:07:29.241-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=9099, name='Python', status='running', started='15:05:38') did not respond to SIGTERM. Trying SIGKILL
[2024-02-27T15:07:29.246-0500] {process_utils.py:86} INFO - Sending the signal 9 to group 9099
[2024-02-27T15:07:29.261-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=9099, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:05:38') (9099) terminated with exit code -9
[2024-02-27T15:07:29.263-0500] {standard_task_runner.py:172} ERROR - Job 71 was killed before it finished (likely due to running out of memory)
