[2024-02-26T11:58:22.977-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_postgres.read_s3_file_task manual__2024-02-26T16:58:20.515539+00:00 [queued]>
[2024-02-26T11:58:22.981-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_postgres.read_s3_file_task manual__2024-02-26T16:58:20.515539+00:00 [queued]>
[2024-02-26T11:58:22.982-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-26T11:58:22.988-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): read_s3_file_task> on 2024-02-26 16:58:20.515539+00:00
[2024-02-26T11:58:22.992-0500] {standard_task_runner.py:57} INFO - Started process 23627 to run task
[2024-02-26T11:58:22.996-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 's3_to_postgres', 'read_s3_file_task', 'manual__2024-02-26T16:58:20.515539+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/S3_to_postgres.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmp522mqt8s']
[2024-02-26T11:58:22.998-0500] {standard_task_runner.py:85} INFO - Job 34: Subtask read_s3_file_task
[2024-02-26T11:58:23.068-0500] {task_command.py:416} INFO - Running <TaskInstance: s3_to_postgres.read_s3_file_task manual__2024-02-26T16:58:20.515539+00:00 [running]> on host venkatasaismbp.hsd1.nj.comcast.net
[2024-02-26T11:58:23.152-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='s3_to_postgres' AIRFLOW_CTX_TASK_ID='read_s3_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T16:58:20.515539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T16:58:20.515539+00:00'
[2024-02-26T11:58:23.169-0500] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'aws_conn_s3', switching to empty.
[2024-02-26T11:58:23.169-0500] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-02-26T11:59:03.630-0500] {local_task_job_runner.py:274} WARNING - Recorded pid 23788 does not match the current pid 23627
[2024-02-26T11:59:03.636-0500] {process_utils.py:131} INFO - Sending 15 to group 23627. PIDs of all processes in the group: [23627]
[2024-02-26T11:59:03.637-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 23627
