[2024-03-01T15:09:21.382-0500] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: etl_customer_dag.extract_customers manual__2024-02-29T21:43:30.430028+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-03-01T15:09:21.385-0500] {local_task_job_runner.py:154} INFO - Task is not able to be run
